export const BLOG_CATEGORIES = [
  'Khata Book',
  'Udhar Management',
  'Expense Tracking',
  'Customer Ledger',
  'Shopkeeper Accounting',
  'Small Business Accounting',
  'Hisaab Kitab',
];

export const BLOG_POSTS = [
  // ── Expense Tracking ──────────────────────────────────────────────────────
  {
    slug: 'expense-tracking-for-small-business',
    title: 'Expense Tracking for Small Business',
    description: 'Use simple routines to capture spending, reduce waste and improve visibility across the month.',
    category: 'Expense Tracking',
    date: '2025-01-10',
    keywords: ['expense tracking', 'small business expenses', 'business expense tracker'],
  },
  {
    slug: 'business-expense-categories',
    title: 'Business Expense Categories: The Complete Guide',
    description: 'How to classify every business expense correctly so your records are organized and your reports are meaningful.',
    category: 'Expense Tracking',
    date: '2025-01-18',
    keywords: ['business expense categories', 'expense classification', 'expense management'],
  },
  {
    slug: 'freelancer-expense-tracking',
    title: 'Freelancer Expense Tracking',
    description: 'Learn how to track invoices, reimbursements, subscriptions and business costs without confusion.',
    category: 'Expense Tracking',
    date: '2025-02-05',
    keywords: ['freelancer expense tracking', 'freelance finance', 'expense tracker app'],
  },
  {
    slug: 'personal-budget-planning',
    title: 'Personal Budget Planning',
    description: 'Build a realistic budget that covers essentials, goals and unexpected costs without stress.',
    category: 'Expense Tracking',
    date: '2025-02-14',
    keywords: ['personal budget planning', 'budget app', 'money management'],
  },
  {
    slug: 'cash-flow-management',
    title: 'Cash Flow Management for Small Businesses',
    description: 'Why profitable businesses run out of cash and the practical habits that keep your cash position healthy.',
    category: 'Expense Tracking',
    date: '2025-03-01',
    keywords: ['cash flow management', 'small business cash flow', 'business finance'],
  },
  {
    slug: 'money-management-tips',
    title: 'Money Management Tips',
    description: 'Use practical habits to improve spending discipline, savings and long-term planning.',
    category: 'Expense Tracking',
    date: '2025-03-10',
    keywords: ['money management tips', 'financial habits', 'expense management app'],
  },
  {
    slug: 'business-finance-tips',
    title: 'Business Finance Tips',
    description: 'Simple ways to improve decision-making, cash flow awareness and recordkeeping discipline.',
    category: 'Expense Tracking',
    date: '2025-03-20',
    keywords: ['business finance tips', 'small business accounting', 'financial management'],
  },
  {
    slug: 'pdf-reports-for-businesses',
    title: 'PDF Reports for Businesses',
    description: 'Understand how professional reports support trust, clarity and easier day-to-day administration.',
    category: 'Expense Tracking',
    date: '2025-04-02',
    keywords: ['pdf reports', 'business reports', 'expense report app'],
  },
  {
    slug: 'why-offline-finance-apps-are-better',
    title: 'Why Offline Finance Apps Are Better',
    description: 'See why offline tools remain powerful in low-connectivity environments and for private financial records.',
    category: 'Expense Tracking',
    date: '2025-04-15',
    keywords: ['offline finance app', 'offline expense tracker', 'no internet accounting'],
  },
  {
    slug: 'how-to-track-daily-expenses',
    title: 'How to Track Daily Expenses',
    description: 'A step-by-step system for recording every rupee spent so nothing slips through the cracks.',
    category: 'Expense Tracking',
    date: '2025-05-01',
    keywords: ['track daily expenses', 'daily expense tracker', 'expense tracker app'],
  },
  {
    slug: 'best-expense-tracker-apps-2025',
    title: 'Best Expense Tracker Apps in 2025',
    description: 'Compare the top expense tracker apps available for Android and find the right one for your needs.',
    category: 'Expense Tracking',
    date: '2025-05-10',
    keywords: ['best expense tracker apps', 'expense tracker 2025', 'expense management app'],
  },
  // ── Khata Book ────────────────────────────────────────────────────────────
  {
    slug: 'how-to-manage-daily-khata',
    title: 'How to Manage Daily Khata',
    description: 'Learn the habits and routines that keep your daily ledger accurate and easy to review.',
    category: 'Khata Book',
    date: '2025-01-05',
    keywords: ['daily khata', 'khata book app', 'digital khata book'],
  },
  {
    slug: 'best-khata-app-in-pakistan',
    title: 'Best Khata App in Pakistan',
    description: 'See what matters most when choosing a local ledger app for your shop, business or household needs.',
    category: 'Khata Book',
    date: '2025-01-25',
    keywords: ['best khata app pakistan', 'khata app', 'digital khata book'],
  },
  {
    slug: 'digital-ledger-vs-paper-ledger',
    title: 'Digital Ledger vs Paper Ledger',
    description: 'Compare traditional bookkeeping with digital systems and see why many businesses are switching.',
    category: 'Khata Book',
    date: '2025-02-08',
    keywords: ['digital ledger', 'paper ledger', 'khata book app'],
  },
  {
    slug: 'bookkeeping-basics',
    title: 'Bookkeeping Basics',
    description: 'Learn the core principles that make financial records more accurate and easier to maintain.',
    category: 'Khata Book',
    date: '2025-02-20',
    keywords: ['bookkeeping basics', 'small business bookkeeping', 'financial records'],
  },
  {
    slug: 'complete-guide-to-hisabdo',
    title: 'Complete Guide to HisabDo',
    description: 'See how HisabDo supports khata management, expense records, backups and reporting in one app.',
    category: 'Khata Book',
    date: '2025-03-05',
    keywords: ['hisabdo guide', 'khata book app', 'expense tracker app'],
  },
  {
    slug: 'what-is-khata-book',
    title: 'What Is a Khata Book?',
    description: 'Understand the traditional khata system and how digital apps are modernizing it for small businesses.',
    category: 'Khata Book',
    date: '2025-05-15',
    keywords: ['what is khata book', 'khata meaning', 'digital khata book'],
  },
  {
    slug: 'khata-book-for-shopkeepers',
    title: 'Khata Book for Shopkeepers',
    description: 'How shopkeepers can use a digital khata book to replace paper registers and reduce errors.',
    category: 'Khata Book',
    date: '2025-05-22',
    keywords: ['khata book shopkeeper', 'shopkeeper accounting app', 'digital khata'],
  },
  {
    slug: 'digital-khata-vs-paper-khata',
    title: 'Digital Khata vs Paper Khata',
    description: 'A practical comparison to help you decide whether to switch from paper to a digital khata system.',
    category: 'Khata Book',
    date: '2025-06-01',
    keywords: ['digital khata', 'paper khata', 'khata book app'],
  },
  // ── Customer Ledger ───────────────────────────────────────────────────────
  {
    slug: 'customer-credit-management',
    title: 'Customer Credit Management',
    description: 'Use better habits and tools to track balances and reduce missed collections from regular customers.',
    category: 'Customer Ledger',
    date: '2025-02-25',
    keywords: ['customer credit management', 'customer ledger app', 'udhar management'],
  },
  {
    slug: 'track-customer-dues',
    title: 'How to Track Customer Dues and Receivables',
    description: 'A practical system to record every credit transaction and follow up on unpaid dues without losing track.',
    category: 'Customer Ledger',
    date: '2025-03-15',
    keywords: ['track customer dues', 'customer ledger', 'receivable tracker'],
  },
  {
    slug: 'receivable-payable-explained',
    title: 'Receivable and Payable Explained',
    description: 'Learn the difference between what is owed to you and what you owe to others, and how to manage both.',
    category: 'Customer Ledger',
    date: '2025-03-25',
    keywords: ['receivable payable', 'accounts receivable', 'receivable and payable tracker'],
  },
  {
    slug: 'how-to-manage-udhar',
    title: 'How to Manage Udhar Effectively',
    description: 'Practical strategies for tracking udhar, following up with customers and reducing unpaid balances.',
    category: 'Customer Ledger',
    date: '2025-06-05',
    keywords: ['manage udhar', 'udhar management app', 'udhar tracker'],
  },
  {
    slug: 'udhar-tracking-for-small-business',
    title: 'Udhar Tracking for Small Business',
    description: 'How small businesses can use a digital system to track udhar and avoid revenue loss.',
    category: 'Customer Ledger',
    date: '2025-06-12',
    keywords: ['udhar tracking', 'udhar management', 'small business udhar app'],
  },
  {
    slug: 'customer-ledger-management-guide',
    title: 'Customer Ledger Management Guide',
    description: 'A complete guide to setting up and maintaining a customer ledger for your business.',
    category: 'Customer Ledger',
    date: '2025-06-20',
    keywords: ['customer ledger management', 'customer ledger app', 'ledger management'],
  },
  {
    slug: 'how-to-reduce-bad-debt',
    title: 'How to Reduce Bad Debt in Your Business',
    description: 'Proven methods to minimize unpaid customer balances and protect your business cash flow.',
    category: 'Customer Ledger',
    date: '2025-07-01',
    keywords: ['reduce bad debt', 'customer credit risk', 'udhar management app'],
  },
  {
    slug: 'accounts-receivable-for-small-business',
    title: 'Accounts Receivable for Small Business',
    description: 'How to set up a simple accounts receivable system that keeps your collections on track.',
    category: 'Customer Ledger',
    date: '2025-07-08',
    keywords: ['accounts receivable', 'receivable tracker', 'customer ledger app'],
  },
  // ── Shopkeeper Management ─────────────────────────────────────────────────
  {
    slug: 'shopkeeper-accounting-guide',
    title: 'Shopkeeper Accounting Guide',
    description: 'Build a practical accounting routine that fits the fast pace of retail and daily customer transactions.',
    category: 'Shopkeeper Accounting',
    date: '2025-04-05',
    keywords: ['shopkeeper accounting', 'shopkeeper accounting app', 'retail accounting'],
  },
  {
    slug: 'supplier-payments-payables',
    title: 'How to Manage Supplier Payments and Payables',
    description: 'Track what you owe, pay on time and maintain strong supplier relationships with a simple payables system.',
    category: 'Shopkeeper Accounting',
    date: '2025-04-20',
    keywords: ['supplier payments', 'accounts payable', 'payable tracker'],
  },
  {
    slug: 'accounts-payable-management',
    title: 'Accounts Payable Management for Shopkeepers',
    description: 'How to track and manage what you owe to suppliers without missing payments.',
    category: 'Shopkeeper Accounting',
    date: '2025-07-15',
    keywords: ['accounts payable', 'payable management', 'shopkeeper accounting app'],
  },
  {
    slug: 'invoice-management-for-shopkeepers',
    title: 'Invoice Management for Shopkeepers',
    description: 'Simple invoice tracking methods that help shopkeepers stay organized and get paid faster.',
    category: 'Shopkeeper Accounting',
    date: '2025-07-22',
    keywords: ['invoice management', 'shopkeeper invoicing', 'small business invoicing'],
  },
  {
    slug: 'daily-sales-tracking-app',
    title: 'Daily Sales Tracking for Shopkeepers',
    description: 'How to record daily sales accurately and use the data to grow your business.',
    category: 'Shopkeeper Accounting',
    date: '2025-08-01',
    keywords: ['daily sales tracking', 'sales tracker app', 'shopkeeper accounting'],
  },
  {
    slug: 'how-to-manage-shop-expenses',
    title: 'How to Manage Shop Expenses',
    description: 'A practical guide for shopkeepers to track and control daily operating expenses.',
    category: 'Shopkeeper Accounting',
    date: '2025-08-08',
    keywords: ['shop expenses', 'shopkeeper expense tracker', 'retail expense management'],
  },
  {
    slug: 'grocery-shop-accounting',
    title: 'Grocery Shop Accounting Made Simple',
    description: 'How grocery shop owners can manage daily transactions, stock costs and customer credit.',
    category: 'Shopkeeper Accounting',
    date: '2025-08-15',
    keywords: ['grocery shop accounting', 'grocery store bookkeeping', 'shopkeeper accounting app'],
  },
  {
    slug: 'retail-store-bookkeeping',
    title: 'Retail Store Bookkeeping Guide',
    description: 'Essential bookkeeping practices every retail store owner should follow.',
    category: 'Shopkeeper Accounting',
    date: '2025-08-22',
    keywords: ['retail store bookkeeping', 'retail accounting', 'shopkeeper accounting'],
  },
  // ── Small Business Accounting ─────────────────────────────────────────────
  {
    slug: 'small-business-financial-management',
    title: 'The Complete Small Business Financial Management Guide',
    description: 'Everything a small business owner needs to know about income, expenses, receivables, payables and cash flow.',
    category: 'Small Business Accounting',
    date: '2025-01-01',
    keywords: ['small business financial management', 'small business accounting software', 'business finance'],
  },
  {
    slug: 'profit-and-loss-for-small-business',
    title: 'Profit and Loss for Small Business',
    description: 'How to calculate and understand your profit and loss without an accountant.',
    category: 'Small Business Accounting',
    date: '2025-07-28',
    keywords: ['profit and loss', 'small business accounting', 'business expense tracker'],
  },
  {
    slug: 'wholesale-business-accounting',
    title: 'Wholesale Business Accounting Guide',
    description: 'Accounting practices tailored for wholesale businesses managing bulk orders and credit customers.',
    category: 'Small Business Accounting',
    date: '2025-08-05',
    keywords: ['wholesale accounting', 'wholesale business finance', 'small business accounting software'],
  },
  {
    slug: 'service-business-expense-tracking',
    title: 'Expense Tracking for Service Businesses',
    description: 'How service-based businesses can track costs, invoices and client payments efficiently.',
    category: 'Small Business Accounting',
    date: '2025-08-12',
    keywords: ['service business expenses', 'service business accounting', 'expense tracker app'],
  },
  {
    slug: 'freelance-income-tracking',
    title: 'Freelance Income Tracking',
    description: 'How freelancers can track multiple income streams and stay on top of their finances.',
    category: 'Small Business Accounting',
    date: '2025-08-19',
    keywords: ['freelance income tracking', 'freelancer finance app', 'income tracker'],
  },
  {
    slug: 'hisabdo-vs-other-khata-apps',
    title: 'HisabDo vs Other Khata Apps',
    description: 'An honest comparison of HisabDo against other popular khata and ledger apps.',
    category: 'Small Business Accounting',
    date: '2025-09-01',
    keywords: ['hisabdo vs khata apps', 'best khata app', 'khata book app comparison'],
  },
  // ── Financial Record Keeping ──────────────────────────────────────────────
  {
    slug: 'how-to-create-financial-reports',
    title: 'How to Create Financial Reports for Your Business',
    description: 'Step-by-step guide to generating useful financial reports that help you make better decisions.',
    category: 'Financial Record Keeping',
    date: '2025-06-25',
    keywords: ['financial reports', 'business reports', 'pdf reports for business'],
  },
  {
    slug: 'backup-financial-data-android',
    title: 'How to Backup Financial Data on Android',
    description: 'Best practices for backing up your business financial records on Android devices.',
    category: 'Financial Record Keeping',
    date: '2025-07-05',
    keywords: ['backup financial data', 'android backup', 'offline finance app'],
  },
  {
    slug: 'multi-currency-expense-tracking',
    title: 'Multi-Currency Expense Tracking',
    description: 'How to manage expenses in PKR, USD and INR within a single app.',
    category: 'Financial Record Keeping',
    date: '2025-07-12',
    keywords: ['multi currency expense tracking', 'pkr usd inr', 'expense tracker app'],
  },
  {
    slug: 'urdu-accounting-app',
    title: 'Urdu Accounting App for Pakistani Businesses',
    description: 'Why an Urdu-language accounting app makes financial management easier for local businesses.',
    category: 'Financial Record Keeping',
    date: '2025-07-18',
    keywords: ['urdu accounting app', 'urdu khata app', 'pakistan accounting app'],
  },
  {
    slug: 'pakistan-small-business-finance',
    title: 'Small Business Finance in Pakistan',
    description: 'Practical financial management advice tailored for small businesses operating in Pakistan.',
    category: 'Financial Record Keeping',
    date: '2025-07-25',
    keywords: ['pakistan small business finance', 'pakistan accounting', 'khata app pakistan'],
  },
  {
    slug: 'india-khata-app-guide',
    title: 'Khata App Guide for Indian Small Businesses',
    description: 'How Indian shopkeepers and small businesses can use a digital khata app to manage finances.',
    category: 'Financial Record Keeping',
    date: '2025-08-02',
    keywords: ['india khata app', 'khata app india', 'digital khata india'],
  },
  {
    slug: 'offline-vs-online-accounting-apps',
    title: 'Offline vs Online Accounting Apps',
    description: 'Compare offline-first and cloud-based accounting apps to find the right fit for your business.',
    category: 'Financial Record Keeping',
    date: '2025-08-09',
    keywords: ['offline accounting app', 'online accounting app', 'offline expense tracker'],
  },
  {
    slug: 'voice-entry-expense-tracking',
    title: 'Voice Entry for Expense Tracking',
    description: 'How voice input makes recording transactions faster and more convenient for busy business owners.',
    category: 'Financial Record Keeping',
    date: '2025-08-16',
    keywords: ['voice entry expense tracking', 'voice input app', 'expense tracker app'],
  },
  {
    slug: 'how-to-export-pdf-reports',
    title: 'How to Export PDF Reports from HisabDo',
    description: 'A step-by-step guide to generating and sharing PDF financial reports from the HisabDo app.',
    category: 'Small Business Accounting',
    date: '2025-08-23',
    keywords: ['export pdf reports', 'pdf financial reports', 'hisabdo reports'],
  },

  // ── 50 Planned Articles ──────────────────────────────────────────────────
  {
    slug: 'what-is-digital-khata-book',
    title: 'What Is a Digital Khata Book? Complete Guide for Shopkeepers',
    description: 'A complete guide explaining what a digital khata book is, how it works and why shopkeepers across Pakistan and India are switching from paper to digital.',
    category: 'Khata Book',
    date: '2025-09-01',
    keywords: ['digital khata book', 'khata book app', 'what is khata book'],
  },
  {
    slug: 'best-way-to-maintain-khata-book',
    title: 'Best Way to Maintain a Khata Book for Your Shop',
    description: 'Practical habits and routines for keeping your shop khata accurate, up to date and easy to review every day.',
    category: 'Khata Book',
    date: '2025-09-05',
    keywords: ['maintain khata book', 'khata book for shopkeepers', 'shop khata app'],
  },
  {
    slug: 'paper-khata-vs-digital-khata',
    title: 'Paper Khata vs Digital Khata: Which Is Better for Shopkeepers?',
    description: 'A practical comparison of paper khata and digital khata apps to help shopkeepers decide which system works better for their business.',
    category: 'Khata Book',
    date: '2025-09-10',
    keywords: ['paper khata vs digital khata', 'digital khata book', 'khata app'],
  },
  {
    slug: 'manage-shop-khata-digitally',
    title: 'How to Manage Your Shop Khata Digitally',
    description: 'Step-by-step guide for shopkeepers on moving their daily khata records from paper to a digital app without disrupting their workflow.',
    category: 'Khata Book',
    date: '2025-09-15',
    keywords: ['manage shop khata digitally', 'digital khata app', 'shop khata app'],
  },
  {
    slug: 'digital-khata-book-for-small-businesses',
    title: 'Digital Khata Book for Small Businesses: Complete Guide',
    description: 'How small businesses can use a digital khata book to organize customer accounts, track payments and reduce errors in daily recordkeeping.',
    category: 'Khata Book',
    date: '2025-09-20',
    keywords: ['digital khata book small business', 'business khata app', 'khata book app'],
  },
  {
    slug: 'how-to-keep-customer-accounts-organized',
    title: 'How to Keep Customer Accounts Organized',
    description: 'Practical methods for organizing customer accounts so you always know who owes what and when payments are due.',
    category: 'Khata Book',
    date: '2025-09-25',
    keywords: ['customer accounts organized', 'customer khata app', 'customer ledger app'],
  },
  {
    slug: 'shopkeepers-moving-to-digital-khata',
    title: 'Why Shopkeepers Are Moving From Paper Khata to Digital Apps',
    description: 'The real reasons shopkeepers across Pakistan and India are replacing paper registers with digital khata apps — and what they gain.',
    category: 'Khata Book',
    date: '2025-09-30',
    keywords: ['shopkeepers digital khata', 'paper to digital khata', 'khata book app'],
  },
  {
    slug: 'khata-book-track-customer-payments',
    title: 'How a Khata Book Helps Track Customer Payments',
    description: 'How maintaining a proper khata book — digital or paper — helps shopkeepers track every customer payment and reduce missed collections.',
    category: 'Khata Book',
    date: '2025-10-05',
    keywords: ['khata book customer payments', 'track customer payments', 'khata app'],
  },
  {
    slug: 'what-is-udhar-book',
    title: 'What Is an Udhar Book and How Does It Work?',
    description: 'A clear explanation of what an udhar book is, how shopkeepers use it to track customer credit and how digital udhar apps improve the process.',
    category: 'Udhar Management',
    date: '2025-10-10',
    keywords: ['udhar book', 'udhar app', 'udhar management app'],
  },
  {
    slug: 'how-to-track-udhar-for-shop',
    title: 'How to Track Udhar for Your Shop',
    description: 'A practical system for recording every udhar transaction, following up with customers and keeping your outstanding dues under control.',
    category: 'Udhar Management',
    date: '2025-10-15',
    keywords: ['track udhar shop', 'udhar tracking app', 'udhar khata app'],
  },
  {
    slug: 'manage-customer-credit-without-paper',
    title: 'How to Manage Customer Credit Without a Paper Register',
    description: 'How to replace your paper udhar register with a digital system that is faster, more accurate and impossible to lose.',
    category: 'Udhar Management',
    date: '2025-10-20',
    keywords: ['manage customer credit', 'customer credit app', 'udhar management app'],
  },
  {
    slug: 'best-way-to-track-customer-udhar',
    title: 'Best Way to Keep Track of Customer Udhar',
    description: 'The most effective methods for tracking customer udhar so nothing gets forgotten and collections stay on schedule.',
    category: 'Udhar Management',
    date: '2025-10-25',
    keywords: ['track customer udhar', 'udhar tracker', 'customer udhar app'],
  },
  {
    slug: 'maintain-udhar-account-for-every-customer',
    title: 'How to Maintain an Udhar Account for Every Customer',
    description: 'How to set up and maintain individual udhar accounts for each customer so balances are always accurate and easy to review.',
    category: 'Udhar Management',
    date: '2025-11-01',
    keywords: ['udhar account customer', 'udhar account app', 'customer ledger app'],
  },
  {
    slug: 'customer-due-tracking-guide',
    title: 'Customer Due Tracking: A Simple Guide for Shopkeepers',
    description: 'A straightforward guide for shopkeepers on tracking customer dues, recording payments and following up on outstanding balances.',
    category: 'Udhar Management',
    date: '2025-11-05',
    keywords: ['customer due tracking', 'customer due tracker', 'udhar management app'],
  },
  {
    slug: 'reduce-forgotten-udhar',
    title: 'How to Reduce Forgotten Udhar and Outstanding Payments',
    description: 'Practical strategies to prevent udhar from being forgotten and ensure outstanding customer payments are collected on time.',
    category: 'Udhar Management',
    date: '2025-11-10',
    keywords: ['reduce forgotten udhar', 'outstanding payments', 'udhar tracking app'],
  },
  {
    slug: 'credit-vs-udhar',
    title: 'Credit vs Udhar: Understanding Customer Credit Records',
    description: 'The difference between formal credit and udhar in a small business context, and how to manage both types of customer records effectively.',
    category: 'Udhar Management',
    date: '2025-11-15',
    keywords: ['credit vs udhar', 'customer credit records', 'udhar app'],
  },
  {
    slug: 'how-to-track-daily-business-expenses',
    title: 'How to Track Daily Business Expenses',
    description: 'A step-by-step system for recording every business expense daily so your records are always accurate and your reports are meaningful.',
    category: 'Expense Tracking',
    date: '2025-11-20',
    keywords: ['track daily business expenses', 'daily expense tracker', 'business expense tracker'],
  },
  {
    slug: 'what-is-expense-management-small-business',
    title: 'What Is Expense Management for Small Businesses?',
    description: 'A clear explanation of expense management for small businesses — what it means, why it matters and how to implement a simple system.',
    category: 'Expense Tracking',
    date: '2025-11-25',
    keywords: ['expense management small business', 'expense management app', 'business expense management'],
  },
  {
    slug: 'why-small-business-needs-expense-tracker',
    title: 'Why Every Small Business Needs an Expense Tracker',
    description: 'The practical reasons why every small business — from a kiryana store to a freelance service — benefits from using an expense tracker.',
    category: 'Expense Tracking',
    date: '2025-12-01',
    keywords: ['small business expense tracker', 'expense tracker app', 'business expense tracking'],
  },
  {
    slug: 'how-to-track-shop-expenses',
    title: 'How to Track Shop Expenses Easily',
    description: 'Simple methods for shopkeepers to record and organize daily shop expenses without complicated software or accounting knowledge.',
    category: 'Expense Tracking',
    date: '2025-12-05',
    keywords: ['track shop expenses', 'shop expense tracker', 'shopkeeper expense app'],
  },
  {
    slug: '10-common-business-expenses-shopkeepers',
    title: '10 Common Business Expenses Every Shopkeeper Should Track',
    description: 'The ten most important expense categories every shopkeeper should record to maintain accurate financial records and understand their costs.',
    category: 'Expense Tracking',
    date: '2025-12-10',
    keywords: ['common business expenses', 'shopkeeper expenses', 'expense categories'],
  },
  {
    slug: 'expense-tracking-improves-cash-flow',
    title: 'How Expense Tracking Improves Small Business Cash Flow',
    description: 'How consistent expense tracking helps small businesses identify waste, improve cash flow and make better financial decisions.',
    category: 'Expense Tracking',
    date: '2025-12-15',
    keywords: ['expense tracking cash flow', 'small business cash flow', 'expense tracker app'],
  },
  {
    slug: 'paper-expense-records-vs-digital',
    title: 'Paper Expense Records vs Digital Expense Tracking',
    description: 'A practical comparison of paper-based expense records and digital expense tracking apps to help small businesses choose the right approach.',
    category: 'Expense Tracking',
    date: '2025-12-20',
    keywords: ['paper expense records vs digital', 'digital expense tracking', 'expense tracker app'],
  },
  {
    slug: 'how-to-organize-daily-business-expenses',
    title: 'How to Organize Daily Business Expenses',
    description: 'A practical guide for organizing daily business expenses by category, date and type so your records are always clean and reportable.',
    category: 'Expense Tracking',
    date: '2025-12-25',
    keywords: ['organize daily business expenses', 'daily expense tracker', 'expense management app'],
  },
  {
    slug: 'business-expense-categories-to-track',
    title: 'Business Expense Categories Every Small Business Should Track',
    description: 'The essential expense categories every small business should use to keep financial records organized and reports meaningful.',
    category: 'Expense Tracking',
    date: '2026-01-05',
    keywords: ['business expense categories', 'expense categories small business', 'expense management app'],
  },
  {
    slug: 'freelancers-track-business-expenses',
    title: 'How Freelancers Can Track Their Business Expenses',
    description: 'A practical guide for freelancers on tracking business expenses, separating personal and professional costs and staying organized for reporting.',
    category: 'Expense Tracking',
    date: '2026-01-10',
    keywords: ['freelancers track business expenses', 'freelancer expense tracker', 'expense tracker app'],
  },
  {
    slug: 'what-is-customer-ledger',
    title: 'What Is a Customer Ledger? Complete Guide',
    description: 'A complete guide to customer ledgers — what they are, how they work and why every business that extends credit needs one.',
    category: 'Customer Ledger',
    date: '2026-01-15',
    keywords: ['what is customer ledger', 'customer ledger app', 'digital customer ledger'],
  },
  {
    slug: 'maintain-customer-ledger-digitally',
    title: 'How to Maintain a Customer Ledger Digitally',
    description: 'Step-by-step guide for maintaining a digital customer ledger — setting up accounts, recording transactions and generating statements.',
    category: 'Customer Ledger',
    date: '2026-01-20',
    keywords: ['maintain customer ledger digitally', 'digital customer ledger', 'customer ledger app'],
  },
  {
    slug: 'customer-ledger-vs-khata-book',
    title: 'Customer Ledger vs Khata Book: What\'s the Difference?',
    description: 'Understanding the difference between a customer ledger and a khata book, and when to use each for your business.',
    category: 'Customer Ledger',
    date: '2026-01-25',
    keywords: ['customer ledger vs khata book', 'customer ledger app', 'khata book app'],
  },
  {
    slug: 'how-to-track-customer-balances',
    title: 'How to Track Customer Balances',
    description: 'Practical methods for tracking outstanding customer balances so you always know who owes you and how much.',
    category: 'Customer Ledger',
    date: '2026-02-01',
    keywords: ['track customer balances', 'customer balance tracker', 'customer ledger app'],
  },
  {
    slug: 'track-customer-payments-and-dues',
    title: 'How to Track Customer Payments and Dues',
    description: 'A simple system for recording customer payments, tracking outstanding dues and following up on overdue balances.',
    category: 'Customer Ledger',
    date: '2026-02-05',
    keywords: ['track customer payments dues', 'customer payment tracker', 'customer due tracker'],
  },
  {
    slug: 'why-shopkeeper-needs-customer-ledger',
    title: 'Why Every Shopkeeper Needs a Customer Ledger',
    description: 'The practical reasons why maintaining a customer ledger is essential for every shopkeeper who extends credit to customers.',
    category: 'Customer Ledger',
    date: '2026-02-10',
    keywords: ['shopkeeper customer ledger', 'customer ledger app', 'ledger app for shopkeepers'],
  },
  {
    slug: 'digital-ledgers-help-small-businesses',
    title: 'How Digital Ledgers Help Small Businesses',
    description: 'How switching from paper to digital ledgers helps small businesses save time, reduce errors and improve financial visibility.',
    category: 'Customer Ledger',
    date: '2026-02-15',
    keywords: ['digital ledgers small business', 'digital ledger app', 'business ledger app'],
  },
  {
    slug: 'keep-customer-transaction-history-organized',
    title: 'How to Keep Customer Transaction History Organized',
    description: 'Best practices for organizing customer transaction history so records are easy to search, review and share.',
    category: 'Customer Ledger',
    date: '2026-02-20',
    keywords: ['customer transaction history', 'customer transaction tracker', 'customer ledger app'],
  },
  {
    slug: 'simple-accounting-for-shopkeepers',
    title: 'Simple Accounting for Shopkeepers: Complete Guide',
    description: 'A complete, practical accounting guide for shopkeepers covering daily sales, expenses, customer credit and supplier payments.',
    category: 'Shopkeeper Accounting',
    date: '2026-03-01',
    keywords: ['simple accounting shopkeepers', 'shopkeeper accounting app', 'accounting app for shopkeepers'],
  },
  {
    slug: 'shopkeepers-manage-daily-accounts',
    title: 'How Shopkeepers Can Manage Daily Accounts',
    description: 'A practical daily accounting routine for shopkeepers to record sales, expenses and customer transactions without missing anything.',
    category: 'Shopkeeper Accounting',
    date: '2026-03-05',
    keywords: ['shopkeepers daily accounts', 'daily accounts app', 'shopkeeper accounting app'],
  },
  {
    slug: '5-financial-records-shopkeepers-should-maintain',
    title: '5 Financial Records Every Shopkeeper Should Maintain',
    description: 'The five most important financial records every shopkeeper should keep to stay organized and make better business decisions.',
    category: 'Shopkeeper Accounting',
    date: '2026-03-10',
    keywords: ['financial records shopkeepers', 'shopkeeper accounting', 'shop bookkeeping app'],
  },
  {
    slug: 'manage-grocery-store-accounts',
    title: 'How to Manage Grocery Store Accounts',
    description: 'A practical guide for grocery store owners on managing daily accounts, customer credit, supplier payments and expenses.',
    category: 'Shopkeeper Accounting',
    date: '2026-03-15',
    keywords: ['grocery store accounts', 'grocery store accounting app', 'kiryana store accounting'],
  },
  {
    slug: 'simple-accounting-kiryana-store',
    title: 'Simple Accounting System for a Kiryana Store',
    description: 'How kiryana store owners can set up a simple, practical accounting system to manage daily transactions without complexity.',
    category: 'Shopkeeper Accounting',
    date: '2026-03-20',
    keywords: ['kiryana store accounting', 'kiryana store accounting app', 'shopkeeper accounting app'],
  },
  {
    slug: 'small-shops-replace-paper-registers',
    title: 'How Small Shops Can Replace Paper Registers',
    description: 'A practical guide for small shop owners on transitioning from paper registers to a digital accounting app without disruption.',
    category: 'Shopkeeper Accounting',
    date: '2026-03-25',
    keywords: ['replace paper registers', 'digital shop accounting', 'shopkeeper accounting app'],
  },
  {
    slug: 'small-business-accounting-beginners-guide',
    title: 'Small Business Accounting: Beginner\'s Guide',
    description: 'A beginner-friendly guide to small business accounting covering the basics of income, expenses, receivables, payables and financial records.',
    category: 'Small Business Accounting',
    date: '2026-04-01',
    keywords: ['small business accounting beginners', 'small business accounting app', 'simple accounting app'],
  },
  {
    slug: 'bookkeeping-vs-accounting-small-business',
    title: 'Bookkeeping vs Accounting for Small Businesses',
    description: 'Understanding the difference between bookkeeping and accounting, and which one your small business actually needs.',
    category: 'Small Business Accounting',
    date: '2026-04-05',
    keywords: ['bookkeeping vs accounting', 'small business bookkeeping', 'small business accounting app'],
  },
  {
    slug: 'better-financial-records-small-business',
    title: 'How to Keep Better Financial Records for a Small Business',
    description: 'Practical steps for improving financial recordkeeping in a small business — from daily habits to report generation.',
    category: 'Small Business Accounting',
    date: '2026-04-10',
    keywords: ['financial records small business', 'small business bookkeeping app', 'business record keeping app'],
  },
  {
    slug: 'small-business-track-income-and-expenses',
    title: 'How Small Businesses Can Track Income and Expenses',
    description: 'A simple, practical system for small businesses to track both income and expenses accurately without complex accounting software.',
    category: 'Small Business Accounting',
    date: '2026-04-15',
    keywords: ['track income and expenses small business', 'small business expense tracker', 'business accounting app'],
  },
  {
    slug: 'simple-financial-management-small-business',
    title: 'Simple Financial Management for Small Business Owners',
    description: 'Practical financial management principles for small business owners who want better control over their money without hiring an accountant.',
    category: 'Small Business Accounting',
    date: '2026-04-20',
    keywords: ['simple financial management small business', 'financial management app small business', 'small business accounting app'],
  },
  {
    slug: 'dukan-ka-hisab-kitab-kaise-manage-karein',
    title: 'Dukan Ka Hisab Kitab Kaise Manage Karein?',
    description: 'Apni dukan ka hisab kitab manage karne ka asaan tareeqa — digital app se rozana ka hisab, customer ka udhar aur expenses track karein.',
    category: 'Hisaab Kitab',
    date: '2026-05-01',
    keywords: ['dukan ka hisab kitab', 'hisab kitab app', 'dukan ka khata app'],
  },
  {
    slug: 'udhar-ka-hisab-rakhne-ka-asaan-tareeqa',
    title: 'Udhar Ka Hisab Rakhne Ka Asaan Tareeqa',
    description: 'Customer ka udhar track karne ka sabse asaan aur reliable tareeqa — paper register ki jagah digital app use karein.',
    category: 'Hisaab Kitab',
    date: '2026-05-05',
    keywords: ['udhar ka hisab', 'udhar app', 'udhar khata app'],
  },
  {
    slug: 'dukaan-ka-khata-digital-kaise-banayein',
    title: 'Dukaan Ka Khata Digital Kaise Banayein?',
    description: 'Apni dukaan ka paper khata digital karne ka step-by-step guide — HisabDo app se customer accounts aur transactions manage karein.',
    category: 'Hisaab Kitab',
    date: '2026-05-10',
    keywords: ['dukaan ka khata digital', 'digital khata app', 'khata book app'],
  },
  {
    slug: 'karobar-ka-hisab-kitab-manage-karne-ka-tareeqa',
    title: 'Karobar Ka Hisab Kitab Manage Karne Ka Asaan Tareeqa',
    description: 'Apne karobar ka hisab kitab manage karne ke liye practical guide — income, expenses, customer ledger aur reports sab ek jagah.',
    category: 'Hisaab Kitab',
    date: '2026-05-15',
    keywords: ['karobar ka hisab kitab', 'hisab kitab app', 'karobar ka hisab app'],
  },
  {
    slug: 'customer-ka-udhar-aur-payment-record',
    title: 'Customer Ka Udhar Aur Payment Record Kaise Rakhein?',
    description: 'Har customer ka udhar aur payment record rakhne ka asaan tareeqa — digital app se accurate records aur PDF statements.',
    category: 'Hisaab Kitab',
    date: '2026-05-20',
    keywords: ['customer ka udhar record', 'customer payment record', 'udhar management app'],
  },
];

export function getPostBySlug(slug) {
  return BLOG_POSTS.find((p) => p.slug === slug) || null;
}

export function getRelatedPosts(slug, limit = 3) {
  const post = getPostBySlug(slug);
  if (!post) return [];
  return BLOG_POSTS.filter(
    (p) => p.slug !== slug && p.category === post.category
  ).slice(0, limit);
}
