export const BLOG_CATEGORIES = [
  'Expense Tracking',
  'Khata Book',
  'Customer Ledger',
  'Shopkeeper Management',
  'Small Business Accounting',
  'Financial Record Keeping',
];

export const BLOG_POSTS = [
  // ── Expense Tracking ──────────────────────────────────────────────────────
  {
    slug: 'expense-tracking-for-small-business',
    title: 'Expense Tracking for Small Business',
    description: 'Use simple routines to capture spending, reduce waste and improve visibility across the month.',
    category: 'Expense Tracking',
    date: '2025-01-10',
    keywords: ['expense tracking', 'small business expenses', 'business expense tracker'],
  },
  {
    slug: 'business-expense-categories',
    title: 'Business Expense Categories: The Complete Guide',
    description: 'How to classify every business expense correctly so your records are organized and your reports are meaningful.',
    category: 'Expense Tracking',
    date: '2025-01-18',
    keywords: ['business expense categories', 'expense classification', 'expense management'],
  },
  {
    slug: 'freelancer-expense-tracking',
    title: 'Freelancer Expense Tracking',
    description: 'Learn how to track invoices, reimbursements, subscriptions and business costs without confusion.',
    category: 'Expense Tracking',
    date: '2025-02-05',
    keywords: ['freelancer expense tracking', 'freelance finance', 'expense tracker app'],
  },
  {
    slug: 'personal-budget-planning',
    title: 'Personal Budget Planning',
    description: 'Build a realistic budget that covers essentials, goals and unexpected costs without stress.',
    category: 'Expense Tracking',
    date: '2025-02-14',
    keywords: ['personal budget planning', 'budget app', 'money management'],
  },
  {
    slug: 'cash-flow-management',
    title: 'Cash Flow Management for Small Businesses',
    description: 'Why profitable businesses run out of cash and the practical habits that keep your cash position healthy.',
    category: 'Expense Tracking',
    date: '2025-03-01',
    keywords: ['cash flow management', 'small business cash flow', 'business finance'],
  },
  {
    slug: 'money-management-tips',
    title: 'Money Management Tips',
    description: 'Use practical habits to improve spending discipline, savings and long-term planning.',
    category: 'Expense Tracking',
    date: '2025-03-10',
    keywords: ['money management tips', 'financial habits', 'expense management app'],
  },
  {
    slug: 'business-finance-tips',
    title: 'Business Finance Tips',
    description: 'Simple ways to improve decision-making, cash flow awareness and recordkeeping discipline.',
    category: 'Expense Tracking',
    date: '2025-03-20',
    keywords: ['business finance tips', 'small business accounting', 'financial management'],
  },
  {
    slug: 'pdf-reports-for-businesses',
    title: 'PDF Reports for Businesses',
    description: 'Understand how professional reports support trust, clarity and easier day-to-day administration.',
    category: 'Expense Tracking',
    date: '2025-04-02',
    keywords: ['pdf reports', 'business reports', 'expense report app'],
  },
  {
    slug: 'why-offline-finance-apps-are-better',
    title: 'Why Offline Finance Apps Are Better',
    description: 'See why offline tools remain powerful in low-connectivity environments and for private financial records.',
    category: 'Expense Tracking',
    date: '2025-04-15',
    keywords: ['offline finance app', 'offline expense tracker', 'no internet accounting'],
  },
  {
    slug: 'how-to-track-daily-expenses',
    title: 'How to Track Daily Expenses',
    description: 'A step-by-step system for recording every rupee spent so nothing slips through the cracks.',
    category: 'Expense Tracking',
    date: '2025-05-01',
    keywords: ['track daily expenses', 'daily expense tracker', 'expense tracker app'],
  },
  {
    slug: 'best-expense-tracker-apps-2025',
    title: 'Best Expense Tracker Apps in 2025',
    description: 'Compare the top expense tracker apps available for Android and find the right one for your needs.',
    category: 'Expense Tracking',
    date: '2025-05-10',
    keywords: ['best expense tracker apps', 'expense tracker 2025', 'expense management app'],
  },
  // ── Khata Book ────────────────────────────────────────────────────────────
  {
    slug: 'how-to-manage-daily-khata',
    title: 'How to Manage Daily Khata',
    description: 'Learn the habits and routines that keep your daily ledger accurate and easy to review.',
    category: 'Khata Book',
    date: '2025-01-05',
    keywords: ['daily khata', 'khata book app', 'digital khata book'],
  },
  {
    slug: 'best-khata-app-in-pakistan',
    title: 'Best Khata App in Pakistan',
    description: 'See what matters most when choosing a local ledger app for your shop, business or household needs.',
    category: 'Khata Book',
    date: '2025-01-25',
    keywords: ['best khata app pakistan', 'khata app', 'digital khata book'],
  },
  {
    slug: 'digital-ledger-vs-paper-ledger',
    title: 'Digital Ledger vs Paper Ledger',
    description: 'Compare traditional bookkeeping with digital systems and see why many businesses are switching.',
    category: 'Khata Book',
    date: '2025-02-08',
    keywords: ['digital ledger', 'paper ledger', 'khata book app'],
  },
  {
    slug: 'bookkeeping-basics',
    title: 'Bookkeeping Basics',
    description: 'Learn the core principles that make financial records more accurate and easier to maintain.',
    category: 'Khata Book',
    date: '2025-02-20',
    keywords: ['bookkeeping basics', 'small business bookkeeping', 'financial records'],
  },
  {
    slug: 'complete-guide-to-hisabdo',
    title: 'Complete Guide to HisabDo',
    description: 'See how HisabDo supports khata management, expense records, backups and reporting in one app.',
    category: 'Khata Book',
    date: '2025-03-05',
    keywords: ['hisabdo guide', 'khata book app', 'expense tracker app'],
  },
  {
    slug: 'what-is-khata-book',
    title: 'What Is a Khata Book?',
    description: 'Understand the traditional khata system and how digital apps are modernizing it for small businesses.',
    category: 'Khata Book',
    date: '2025-05-15',
    keywords: ['what is khata book', 'khata meaning', 'digital khata book'],
  },
  {
    slug: 'khata-book-for-shopkeepers',
    title: 'Khata Book for Shopkeepers',
    description: 'How shopkeepers can use a digital khata book to replace paper registers and reduce errors.',
    category: 'Khata Book',
    date: '2025-05-22',
    keywords: ['khata book shopkeeper', 'shopkeeper accounting app', 'digital khata'],
  },
  {
    slug: 'digital-khata-vs-paper-khata',
    title: 'Digital Khata vs Paper Khata',
    description: 'A practical comparison to help you decide whether to switch from paper to a digital khata system.',
    category: 'Khata Book',
    date: '2025-06-01',
    keywords: ['digital khata', 'paper khata', 'khata book app'],
  },
  // ── Customer Ledger ───────────────────────────────────────────────────────
  {
    slug: 'customer-credit-management',
    title: 'Customer Credit Management',
    description: 'Use better habits and tools to track balances and reduce missed collections from regular customers.',
    category: 'Customer Ledger',
    date: '2025-02-25',
    keywords: ['customer credit management', 'customer ledger app', 'udhar management'],
  },
  {
    slug: 'track-customer-dues',
    title: 'How to Track Customer Dues and Receivables',
    description: 'A practical system to record every credit transaction and follow up on unpaid dues without losing track.',
    category: 'Customer Ledger',
    date: '2025-03-15',
    keywords: ['track customer dues', 'customer ledger', 'receivable tracker'],
  },
  {
    slug: 'receivable-payable-explained',
    title: 'Receivable and Payable Explained',
    description: 'Learn the difference between what is owed to you and what you owe to others, and how to manage both.',
    category: 'Customer Ledger',
    date: '2025-03-25',
    keywords: ['receivable payable', 'accounts receivable', 'receivable and payable tracker'],
  },
  {
    slug: 'how-to-manage-udhar',
    title: 'How to Manage Udhar Effectively',
    description: 'Practical strategies for tracking udhar, following up with customers and reducing unpaid balances.',
    category: 'Customer Ledger',
    date: '2025-06-05',
    keywords: ['manage udhar', 'udhar management app', 'udhar tracker'],
  },
  {
    slug: 'udhar-tracking-for-small-business',
    title: 'Udhar Tracking for Small Business',
    description: 'How small businesses can use a digital system to track udhar and avoid revenue loss.',
    category: 'Customer Ledger',
    date: '2025-06-12',
    keywords: ['udhar tracking', 'udhar management', 'small business udhar app'],
  },
  {
    slug: 'customer-ledger-management-guide',
    title: 'Customer Ledger Management Guide',
    description: 'A complete guide to setting up and maintaining a customer ledger for your business.',
    category: 'Customer Ledger',
    date: '2025-06-20',
    keywords: ['customer ledger management', 'customer ledger app', 'ledger management'],
  },
  {
    slug: 'how-to-reduce-bad-debt',
    title: 'How to Reduce Bad Debt in Your Business',
    description: 'Proven methods to minimize unpaid customer balances and protect your business cash flow.',
    category: 'Customer Ledger',
    date: '2025-07-01',
    keywords: ['reduce bad debt', 'customer credit risk', 'udhar management app'],
  },
  {
    slug: 'accounts-receivable-for-small-business',
    title: 'Accounts Receivable for Small Business',
    description: 'How to set up a simple accounts receivable system that keeps your collections on track.',
    category: 'Customer Ledger',
    date: '2025-07-08',
    keywords: ['accounts receivable', 'receivable tracker', 'customer ledger app'],
  },
  // ── Shopkeeper Management ─────────────────────────────────────────────────
  {
    slug: 'shopkeeper-accounting-guide',
    title: 'Shopkeeper Accounting Guide',
    description: 'Build a practical accounting routine that fits the fast pace of retail and daily customer transactions.',
    category: 'Shopkeeper Management',
    date: '2025-04-05',
    keywords: ['shopkeeper accounting', 'shopkeeper accounting app', 'retail accounting'],
  },
  {
    slug: 'supplier-payments-payables',
    title: 'How to Manage Supplier Payments and Payables',
    description: 'Track what you owe, pay on time and maintain strong supplier relationships with a simple payables system.',
    category: 'Shopkeeper Management',
    date: '2025-04-20',
    keywords: ['supplier payments', 'accounts payable', 'payable tracker'],
  },
  {
    slug: 'accounts-payable-management',
    title: 'Accounts Payable Management for Shopkeepers',
    description: 'How to track and manage what you owe to suppliers without missing payments.',
    category: 'Shopkeeper Management',
    date: '2025-07-15',
    keywords: ['accounts payable', 'payable management', 'shopkeeper accounting app'],
  },
  {
    slug: 'invoice-management-for-shopkeepers',
    title: 'Invoice Management for Shopkeepers',
    description: 'Simple invoice tracking methods that help shopkeepers stay organized and get paid faster.',
    category: 'Shopkeeper Management',
    date: '2025-07-22',
    keywords: ['invoice management', 'shopkeeper invoicing', 'small business invoicing'],
  },
  {
    slug: 'daily-sales-tracking-app',
    title: 'Daily Sales Tracking for Shopkeepers',
    description: 'How to record daily sales accurately and use the data to grow your business.',
    category: 'Shopkeeper Management',
    date: '2025-08-01',
    keywords: ['daily sales tracking', 'sales tracker app', 'shopkeeper accounting'],
  },
  {
    slug: 'how-to-manage-shop-expenses',
    title: 'How to Manage Shop Expenses',
    description: 'A practical guide for shopkeepers to track and control daily operating expenses.',
    category: 'Shopkeeper Management',
    date: '2025-08-08',
    keywords: ['shop expenses', 'shopkeeper expense tracker', 'retail expense management'],
  },
  {
    slug: 'grocery-shop-accounting',
    title: 'Grocery Shop Accounting Made Simple',
    description: 'How grocery shop owners can manage daily transactions, stock costs and customer credit.',
    category: 'Shopkeeper Management',
    date: '2025-08-15',
    keywords: ['grocery shop accounting', 'grocery store bookkeeping', 'shopkeeper accounting app'],
  },
  {
    slug: 'retail-store-bookkeeping',
    title: 'Retail Store Bookkeeping Guide',
    description: 'Essential bookkeeping practices every retail store owner should follow.',
    category: 'Shopkeeper Management',
    date: '2025-08-22',
    keywords: ['retail store bookkeeping', 'retail accounting', 'shopkeeper accounting'],
  },
  // ── Small Business Accounting ─────────────────────────────────────────────
  {
    slug: 'small-business-financial-management',
    title: 'The Complete Small Business Financial Management Guide',
    description: 'Everything a small business owner needs to know about income, expenses, receivables, payables and cash flow.',
    category: 'Small Business Accounting',
    date: '2025-01-01',
    keywords: ['small business financial management', 'small business accounting software', 'business finance'],
  },
  {
    slug: 'profit-and-loss-for-small-business',
    title: 'Profit and Loss for Small Business',
    description: 'How to calculate and understand your profit and loss without an accountant.',
    category: 'Small Business Accounting',
    date: '2025-07-28',
    keywords: ['profit and loss', 'small business accounting', 'business expense tracker'],
  },
  {
    slug: 'wholesale-business-accounting',
    title: 'Wholesale Business Accounting Guide',
    description: 'Accounting practices tailored for wholesale businesses managing bulk orders and credit customers.',
    category: 'Small Business Accounting',
    date: '2025-08-05',
    keywords: ['wholesale accounting', 'wholesale business finance', 'small business accounting software'],
  },
  {
    slug: 'service-business-expense-tracking',
    title: 'Expense Tracking for Service Businesses',
    description: 'How service-based businesses can track costs, invoices and client payments efficiently.',
    category: 'Small Business Accounting',
    date: '2025-08-12',
    keywords: ['service business expenses', 'service business accounting', 'expense tracker app'],
  },
  {
    slug: 'freelance-income-tracking',
    title: 'Freelance Income Tracking',
    description: 'How freelancers can track multiple income streams and stay on top of their finances.',
    category: 'Small Business Accounting',
    date: '2025-08-19',
    keywords: ['freelance income tracking', 'freelancer finance app', 'income tracker'],
  },
  {
    slug: 'hisabdo-vs-other-khata-apps',
    title: 'HisabDo vs Other Khata Apps',
    description: 'An honest comparison of HisabDo against other popular khata and ledger apps.',
    category: 'Small Business Accounting',
    date: '2025-09-01',
    keywords: ['hisabdo vs khata apps', 'best khata app', 'khata book app comparison'],
  },
  // ── Financial Record Keeping ──────────────────────────────────────────────
  {
    slug: 'how-to-create-financial-reports',
    title: 'How to Create Financial Reports for Your Business',
    description: 'Step-by-step guide to generating useful financial reports that help you make better decisions.',
    category: 'Financial Record Keeping',
    date: '2025-06-25',
    keywords: ['financial reports', 'business reports', 'pdf reports for business'],
  },
  {
    slug: 'backup-financial-data-android',
    title: 'How to Backup Financial Data on Android',
    description: 'Best practices for backing up your business financial records on Android devices.',
    category: 'Financial Record Keeping',
    date: '2025-07-05',
    keywords: ['backup financial data', 'android backup', 'offline finance app'],
  },
  {
    slug: 'multi-currency-expense-tracking',
    title: 'Multi-Currency Expense Tracking',
    description: 'How to manage expenses in PKR, USD and INR within a single app.',
    category: 'Financial Record Keeping',
    date: '2025-07-12',
    keywords: ['multi currency expense tracking', 'pkr usd inr', 'expense tracker app'],
  },
  {
    slug: 'urdu-accounting-app',
    title: 'Urdu Accounting App for Pakistani Businesses',
    description: 'Why an Urdu-language accounting app makes financial management easier for local businesses.',
    category: 'Financial Record Keeping',
    date: '2025-07-18',
    keywords: ['urdu accounting app', 'urdu khata app', 'pakistan accounting app'],
  },
  {
    slug: 'pakistan-small-business-finance',
    title: 'Small Business Finance in Pakistan',
    description: 'Practical financial management advice tailored for small businesses operating in Pakistan.',
    category: 'Financial Record Keeping',
    date: '2025-07-25',
    keywords: ['pakistan small business finance', 'pakistan accounting', 'khata app pakistan'],
  },
  {
    slug: 'india-khata-app-guide',
    title: 'Khata App Guide for Indian Small Businesses',
    description: 'How Indian shopkeepers and small businesses can use a digital khata app to manage finances.',
    category: 'Financial Record Keeping',
    date: '2025-08-02',
    keywords: ['india khata app', 'khata app india', 'digital khata india'],
  },
  {
    slug: 'offline-vs-online-accounting-apps',
    title: 'Offline vs Online Accounting Apps',
    description: 'Compare offline-first and cloud-based accounting apps to find the right fit for your business.',
    category: 'Financial Record Keeping',
    date: '2025-08-09',
    keywords: ['offline accounting app', 'online accounting app', 'offline expense tracker'],
  },
  {
    slug: 'voice-entry-expense-tracking',
    title: 'Voice Entry for Expense Tracking',
    description: 'How voice input makes recording transactions faster and more convenient for busy business owners.',
    category: 'Financial Record Keeping',
    date: '2025-08-16',
    keywords: ['voice entry expense tracking', 'voice input app', 'expense tracker app'],
  },
  {
    slug: 'how-to-export-pdf-reports',
    title: 'How to Export PDF Reports from HisabDo',
    description: 'A step-by-step guide to generating and sharing PDF financial reports from the HisabDo app.',
    category: 'Financial Record Keeping',
    date: '2025-08-23',
    keywords: ['export pdf reports', 'pdf financial reports', 'hisabdo reports'],
  },
];

export function getPostBySlug(slug) {
  return BLOG_POSTS.find((p) => p.slug === slug) || null;
}

export function getRelatedPosts(slug, limit = 3) {
  const post = getPostBySlug(slug);
  if (!post) return [];
  return BLOG_POSTS.filter(
    (p) => p.slug !== slug && p.category === post.category
  ).slice(0, limit);
}
